"""Couche événementielle V3 : attendus vs réels, écarts, qualification."""

from pilotage_flux.events_v3.expected import (
    ExpectedEvent,
    fetch_expected,
    generate_expected_from_batch,
    list_expected,
)
from pilotage_flux.events_v3.matching import (
    Deviation,
    KIND_MISSING,
    KIND_QTY,
    KIND_TIME,
    KIND_UNEXPECTED,
    list_deviations,
    match_actuals_to_expected,
)
from pilotage_flux.events_v3.cpm import (
    CpmAbsorption,
    DEFAULT_MARGIN_MINUTES,
    apply_cpm_absorption,
)
from pilotage_flux.events_v3.root_causes import (
    CauseAttachment,
    RootCauseRule,
    attach_causes_to_deviation,
    confirm_cause,
    list_active_rules,
    list_causes_for_deviation,
    top_causes_across_deviations,
)
from pilotage_flux.events_v3.dual_tolerance import (
    ACTION_CORRECT_LOCAL,
    ACTION_ESCALATE,
    ACTION_INFORM,
    ACTION_LEVELS,
    ACTION_REPLAN_GLOBAL,
    ACTION_REPLAN_LOCAL,
    ACTION_WATCH,
    ToleranceDecision,
    evaluate_all_open_deviations,
    evaluate_dual_tolerance,
    list_decisions,
    trigger_pending_decisions,
)
from pilotage_flux.events_v3.dual_memory import (
    DEFAULT_LEARN_THRESHOLD,
    DEFAULT_MIN_RECURRENCE_SHORTCUT,
    MemoryDecision,
    MemoryRecipe,
    capture_recipe,
    list_memory_decisions,
    list_recipes,
    try_memory_shortcut,
    update_parameter_from_learning,
)

__all__ = [
    "ExpectedEvent",
    "fetch_expected",
    "generate_expected_from_batch",
    "list_expected",
    "Deviation",
    "KIND_MISSING",
    "KIND_QTY",
    "KIND_TIME",
    "KIND_UNEXPECTED",
    "list_deviations",
    "match_actuals_to_expected",
    "CpmAbsorption",
    "DEFAULT_MARGIN_MINUTES",
    "apply_cpm_absorption",
    "CauseAttachment",
    "RootCauseRule",
    "attach_causes_to_deviation",
    "confirm_cause",
    "list_active_rules",
    "list_causes_for_deviation",
    "top_causes_across_deviations",
    "ACTION_CORRECT_LOCAL",
    "ACTION_ESCALATE",
    "ACTION_INFORM",
    "ACTION_LEVELS",
    "ACTION_REPLAN_GLOBAL",
    "ACTION_REPLAN_LOCAL",
    "ACTION_WATCH",
    "ToleranceDecision",
    "evaluate_all_open_deviations",
    "evaluate_dual_tolerance",
    "list_decisions",
    "trigger_pending_decisions",
    "DEFAULT_LEARN_THRESHOLD",
    "DEFAULT_MIN_RECURRENCE_SHORTCUT",
    "MemoryDecision",
    "MemoryRecipe",
    "capture_recipe",
    "list_memory_decisions",
    "try_memory_shortcut",
    "list_recipes",
    "update_parameter_from_learning",
]
