"""MACRS — Matrice d'Analyse des Causes Racines Structurée.

Référence : matrice_incidence_causale.md (Couche 1) +
            matrice_operationnelle_specification.md (Couche 2).

Couche 1 (statique) : `macrs_racines` × `macrs_categories` × `macrs_incidence`
    — 46 racines R001..R046, 7 catégories Δ, 175 cellules actives.

Couche 2 (dynamique) : `causal_cells` + agrégats temporels
    — alimente le Pareto hiérarchique et le moteur Delta.
"""

from pilotage_flux.cybernetic.macrs.couche1 import (
    CATEGORIES,
    RACINES,
    seed_macrs_layer1,
    count_incidences,
    list_racines,
    list_categories,
    get_incidences_for_racine,
    get_racines_for_category,
)
from pilotage_flux.cybernetic.macrs.couche2 import (
    BIN_LABELS,
    BINS,
    K_DEFAULT,
    STATUS_ACTIVE,
    STATUS_INCOMING,
    STATUS_OBSERVING,
    STATUSES,
    W_COURTE_DAYS,
    W_LONGUE_DAYS,
    CausalCell,
    CellAggregates,
    aggregate_cell,
    aggregate_cell_by_couple,
    count_cells_by_status,
    delay_to_bin,
    get_cell,
    get_k_for_subdomain,
    init_cells_from_layer1,
    list_cells_by_status,
    list_events_in_window,
    record_event,
)
from pilotage_flux.cybernetic.macrs.snapshots import (
    WV_ACTIVE,
    WV_ARCHIVED,
    WV_EXPERIMENTAL,
    WV_STATUSES,
    CellSnapshot,
    WeightVersion,
    activate_weight_version,
    archive_weight_version,
    count_snapshots,
    create_weight_version,
    get_active_weight_version,
    get_snapshots_for_cell,
    list_snapshots_at,
    list_weight_versions,
    take_snapshot,
)
from pilotage_flux.cybernetic.macrs.pareto import (
    CriticityEntry,
    EmergingRacine,
    ParetoCategoryEntry,
    ParetoRacineEntry,
    detect_declining_racines,
    detect_emerging_racines,
    pareto_categories,
    pareto_criticite,
    pareto_racines,
    pareto_racines_in_category,
)

__all__ = [
    "CATEGORIES",
    "RACINES",
    "seed_macrs_layer1",
    "count_incidences",
    "list_racines",
    "list_categories",
    "get_incidences_for_racine",
    "get_racines_for_category",
    "BIN_LABELS",
    "BINS",
    "K_DEFAULT",
    "STATUS_ACTIVE",
    "STATUS_INCOMING",
    "STATUS_OBSERVING",
    "STATUSES",
    "W_COURTE_DAYS",
    "W_LONGUE_DAYS",
    "CausalCell",
    "CellAggregates",
    "aggregate_cell",
    "aggregate_cell_by_couple",
    "count_cells_by_status",
    "delay_to_bin",
    "get_cell",
    "get_k_for_subdomain",
    "init_cells_from_layer1",
    "list_cells_by_status",
    "list_events_in_window",
    "record_event",
    "WV_ACTIVE",
    "WV_ARCHIVED",
    "WV_EXPERIMENTAL",
    "WV_STATUSES",
    "CellSnapshot",
    "WeightVersion",
    "activate_weight_version",
    "archive_weight_version",
    "count_snapshots",
    "create_weight_version",
    "get_active_weight_version",
    "get_snapshots_for_cell",
    "list_snapshots_at",
    "list_weight_versions",
    "take_snapshot",
    "CriticityEntry",
    "EmergingRacine",
    "ParetoCategoryEntry",
    "ParetoRacineEntry",
    "detect_declining_racines",
    "detect_emerging_racines",
    "pareto_categories",
    "pareto_criticite",
    "pareto_racines",
    "pareto_racines_in_category",
]
